services:
  db:
    image: postgres  
    ports: 
      - ${DB_PORT}:${DB_PORT}
    env_file: .env
  web:
    ports: 
      - ${PORT}:${PORT}
    environment:
      - DB_HOST=db
    build:
      dockerfile: Dockerfile 
