services:
  db:
    image: postgres  
    ports: 
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  web:
    ports: 
      - ${PORT}:${PORT}
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - PORT=${PORT}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - NODE_ENV=${NODE_ENV}
      - JWT_KEY=${JWT_KEY}
    build:
      dockerfile: Dockerfile
