#!/bin/bash
PATH=./node_modules/.bin:$PATH

type-gen() {
  sql-ts -c ./db.json
}

db() {
  knex "${@:1}"
}

migrate() {
  knex migrate:latest
  type-gen
}

init() {
  wait-for-it db:5432
  migrate
  knex seed:run
}

--help() {
  echo "commands:"
  compgen -A function | cat -n
}

"$@"