#!/bin/bash
PATH=./node_modules/.bin:$PATH

type-gen() {
  ts-node -T entities/generate-d.ts
}

db() {
  knex $@
}


migrate() {
  echo 'starting migration..'
  knex migrate:latest || exit $?
  echo 'generating typescript definition for entities..'
  type-gen
}

print-db() {
  node -r ts-node/register/transpile-only <<'EOF'
  const { connect: { connection: db } } = require('./knexfile')
  console.log(`${db.host}:${db.port}`)
EOF
}

init() {
  wait-for-it `print-db`
  migrate || exit $?
  knex seed:run || true
}

--help() {
  echo "commands:"
  compgen -A function | cat -n
}

${@:-'--help'}
