#!/bin/bash
PATH=./node_modules/.bin:$PATH

type-gen() {
  ts-node -T entities/generate-d.ts
}

db() {
  knex "${@:1}"
}

migrate() {
  echo 'starting migration..'
  knex migrate:latest || { exit 1; }
  echo 'generating typescript definition for entities..'
  type-gen || { exit 1; }
}

print-db() {
  ts-node -T <<'EOF'
    import { db } from './knexfile'
    console.log(`${db.host}:${db.port}`)
EOF
}

init() {
  wait-for-it `print-db` || { exit 1; }
  migrate
  echo 'seeding db..'
  knex seed:run
}

--help() {
  echo "commands:"
  compgen -A function | cat -n
}

"$@"
