#!/bin/bash
PATH=./node_modules/.bin:$PATH

type-gen() {
  ts-node -T entities/generate-d.ts
}

db() {
  knex "${@:1}"
}

migrate() {
  echo 'starting migration..'
  knex migrate:latest || { exit 1; }
  echo 'generating typescript definition for entities..'
  type-gen || { exit 1; }
}

init() {
  wait-for-it ${DB_HOST:-localhost}:${DB_PORT:-5432} || { exit 1; }
  migrate
  echo 'seeding db..'
  knex seed:run
}

--help() {
  echo "commands:"
  compgen -A function | cat -n
}

"$@"
